### ISSUE TITLE
POP_JUMP_IF_TRUE cannot be handled correctly

### ISSUE THREAD

**Issue by xxulin** [dude719/unpyclib27#1]
This is the only tool I found for version 2.7, but it doesn't seem to handle POP_JUMP_IF_TRUE correctly. Can you fix it please?

>>> dis.dis(mars)
 10           0 EXTENDED_ARG             0
              3 LOAD_CONST              2L (210651692)
              6 EXTENDED_ARG             0
              9 STORE_FAST              0L (___<zone>___)
             12 EXTENDED_ARG             0
             15 JUMP_FORWARD            0L (to 18L)
        >>   18 EXTENDED_ARG             0
             21 LOAD_CONST              3L (2111012352)
             24 EXTENDED_ARG             0
             27 LOAD_FAST               0L (___<zone>___)
             30 COMPARE_OP               2 (==)
             33 EXTENDED_ARG             0
             36 POP_JUMP_IF_TRUE       90L
             39 EXTENDED_ARG             0
             42 LOAD_CONST              2L (210651692)
             45 EXTENDED_ARG             0
             48 LOAD_FAST               0L (___<zone>___)
             51 COMPARE_OP               2 (==)
             54 EXTENDED_ARG             0
             57 POP_JUMP_IF_TRUE       67L
             60 EXTENDED_ARG             0
             63 LOAD_CONST              4L (None)
             66 RETURN_VALUE
        >>   67 LOAD_CONST               1 ('bbbbbbb')
             70 PRINT_ITEM
             71 PRINT_NEWLINE
             72 EXTENDED_ARG             0
             75 LOAD_CONST              3L (2111012352)
             78 EXTENDED_ARG             0
             81 STORE_FAST              0L (___<zone>___)
             84 EXTENDED_ARG             0
             87 JUMP_ABSOLUTE          18L
        >>   90 LOAD_CONST               0 (None)
             93 RETURN_VALUE

**Comment by ajkhoury** [comment]
This is quite antiquated. Try using this instead: https://pypi.org/project/uncompyle6/
